### ISSUE TITLE
Env variables are not set in production build

### ISSUE THREAD

**Issue by harrygr** [ElMassimo/vite-plugin-environment#1]
It seems like env variables accessed via `process.env` are not substituted in the production build.

Steps to reproduce:

1. Configure Vite project to use `vite-plugin-environment`
1. Reference the env variable somewhere in source code. E.g. 
    ```
   // index.ts
   const myVar = process.env.VITE_FOO
   ```
1. Export an env variable with an allowable name as defined in the plugin config. E.g. `export VITE_FOO=bar` assuming `EnvironmentPlugin('all', { prefix: 'VITE_' })`
1. Run `yarn build`
1. Examine the bundle that's output to see if the value of the env var has been substituted in source code.
1. Observe that the value of `VITE_FOO` is not present in source code.

**Comment by ElMassimo** [comment]
This behavior is intentional, as it's more aligned with the default behavior in Vite and prevents leaking global environment variables.

To use global environment variables instead of env files, pass [`loadEnvFiles: false`](https://github.com/ElMassimo/vite-plugin-environment/blob/main/src/index.ts#L40).

Let me know how it goes 😃

**Comment by harrygr** [comment]
Sorry, I revised my issue and it wasn't fully accurate. The real issue is that env variables accessed in the source code using `process.env` are not statically replaced in the production bundle. 

The default Vite behaviour is that it substitutes references to env values in `import.meta.env` with the allowed prefix (`VITE_`) with their literal values. With this plugin I'd expect the same behaviour but for `process.env` instead of `import.meta.env`

This is a problem regardless of whether the env values are from the global environment or declared in a .env file.

**Comment by ElMassimo** [comment]
Gotcha, please provide a repo with a minimal reproduction (let's focus on one with env files first).

**Comment by harrygr** [comment]
OK apologies. I had an `define` override in my `vite.config.js` that was setting the value of `process.env` to `{}`.

Somehow this was only affecting the prod build.

**Comment by ElMassimo** [comment]
Config is tricky, thanks for sharing what was causing the problem!

**Comment by snake-py** [comment]
I am facing this issue as well - in production build I am getting Uncaught ReferenceError: process is not defined

```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { ViteAliases } from 'vite-aliases'
import EnvironmentPlugin from 'vite-plugin-environment'


export default defineConfig({
  plugins: [react(), ViteAliases(), EnvironmentPlugin('all', { loadEnvFiles: true })],
})
```

**Comment by ElMassimo** [comment]
@snake-py [Different root cause](https://adambien.blog/roller/abien/entry/uncaught_referenceerror_process_is_not).

Seems like a missing environment variable in your production build, so it's not replaced in the source.

It's highly recommended that you [specify defaults](https://github.com/ElMassimo/vite-plugin-environment#usage-with-default-values), using `undefined` if you want the build to fail if the env var is missing.

You could also combine these "required" env vars with an `.env.local` file to specify default values during development.

**Comment by snake-py** [comment]
@ElMassimo , thank you for your reply - The problem was this log stmt: `console.log('env', process.env);` This was not replaced - not sure why.

**Comment by ElMassimo** [comment]
@snake-py Replacement is performed using [`define`](https://vitejs.dev/config/#define):

> Because it's implemented as straightforward text replacements without any syntax analysis, we recommend using define for CONSTANTS only.

That means that `process.env` won't be injected as a constant with values. Instead, `process.env.MY_VAR` will be replaced statically with the provided value.

**Comment by snake-py** [comment]
@ElMassimo Thank you for your explanation. :) it is working now.

**Comment by geremsadaimary** [comment]
Hi, I am facing this issue in staging environment
command: `vite build --mode staging`
I am using this config:
```
EnvironmentPlugin("all", {
      prefix: "REACT_APP_",
    })
```
