### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by pitgrap** [ElMassimo/vite-plugin-environment#11]
I'm using 

- "vite": "^3.1.8",
- "vite-plugin-environment": "^1.1.3"

with React and switched from "create-react-app".

In my config I added `EnvironmentPlugin("all", { prefix: "REACT_APP_" }),`.

If I add an `REACT_APP_something` to my `.env` file everything works, but if my `.env` file is empty, I get the `Uncaught ReferenceError: process is not defined`.

In my code I have a check like `if (process.env.REACT_APP_PREVIEW === "true")` but the env variable is optional.

I expected, that even with no prefixed variable the `process` variable is available.

As workaround I added `EnvironmentPlugin("all", { prefix: "NODE_" }),` because this is always defined, so `process` is defined too.

**Comment by ElMassimo** [comment]
@[pitgrap Replacement is performed using [`define`](https://vitejs.dev/config/shared-options.html#define):

> Because it's implemented as straightforward text replacements without any syntax analysis, we recommend using define for CONSTANTS only.

That means that `process.env` won't be injected as a constant with values. Instead, `process.env.MY_VAR` will be replaced statically with the provided value.

If you want to fail if a particular variable is missing, or provide a default so that you can omit it, use the object format this plugin allows (instead of `all`).
