### ISSUE TITLE
Question regarding build 

### ISSUE THREAD

**Issue by Madvinking** [ElMassimo/vite-plugin-environment#3]
is the process.env object should also include in the bundled version?

**Comment by ElMassimo** [comment]
Hi @Madvinking, not sure if I understood correctly, let me know.

---

This plugin uses the [`define`](https://vitejs.dev/config/#define) config option in Vite to replace occurrences in the code with the specified constant.

>  `define` is implemented as straightforward text replacements without any syntax analysis

Because of this, `process.env` itself won't be an object at runtime and won't be available.
