### ISSUE TITLE
variables only load if I run dotenv before

### ISSUE THREAD

**Issue by Claudi0-V** [ElMassimo/vite-plugin-environment#5]
I'm trying to run this plugin but everytime that I run it returns me the error:
```
error when starting dev server:
Error: vite-plugin-environment: the `API_KEY` environment variable is undefined.
```
i'm running with the config provided in the README.md;

however, if I run:
```js
import dotenv from 'dotenv';
dotenv.config();
```
before `defineConfig` those errors disappears .

edit: here is my whole config:
```js
import { defineConfig } from "vite";
import EnvironmentPlugin from "vite-plugin-environment";
import dotenv from "dotenv";
dotenv.config();

export default defineConfig({
  plugins: [EnvironmentPlugin(["API_KEY", "DEBUG"])],
  root: "src",
  build: {
    // Relative to the root
    outDir: "../dist",
  },
});
```

**Comment by ElMassimo** [comment]
Hi @Claudi0-V!

Running `dotenv` before is a red herring. The error is caused by the use of `root`.

---

There are only two possible options the plugin can take to resolve `.env` files:

- Always use `process.cwd()` as the root
- Use Vite's root

Both have pros and cons, and there's no right answer, it will depend on how a project is structured.

This plugin uses the latter, [calling Vite's `loadEnv`](https://github.com/ElMassimo/vite-plugin-environment/blob/main/src/index.ts#L78) with the config value of `root`.

In your example, it's expecting `.env` files to be located inside the `src` dir.

---

Happy to take a PR to allow specifying the root explicitly in the `options` of this plugin, allowing you to load `.env` files from a different location:

```js
  root: "src",
  plugins: [EnvironmentPlugin(["API_KEY", "DEBUG"], { root: __dirname })],
```

**Comment by Claudi0-V** [comment]
hey @ElMassimo, i trully appreciate your fast answer.

I moved the .env file to the src folder and is still returning the same error to me.

**Comment by ElMassimo** [comment]
Please share a minimal reproduction in a sample repo, and I'll take a look.

**Comment by Claudi0-V** [comment]
I apologize for the late response but I had some health issues. I just tested and after the last update things are working properly. I really appreciate your work man
